# -*- coding: utf-8 -*-
"""Movies-Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14k_1G99fZZT3xJ-sGRMjFtxvZYMDVh-B
"""

MENU_PROMPT = "\nEnter 'a' to add a movie, \n'l' to see your movies, \n'f' to find a movie by title, or 'q' to quit: "
movies = []
# You may want to create a function for this code
def add():
    title = input("Enter the movie title: ")
    director = input("Enter the movie director: ")
    year = input("Enter the movie release year: ")
    location = input("Enter the movie Location: ")
    movies.append({
     'title': title,
     'director': director,
     'year': year,
     'location':location
    })
# Create other functions for:
# - listing movies
def listMovies():
    for i in movies:
        print(i)

# - finding movies
def findMovie(movieName):
    for i in movies:
        if i['title']==movieName:
            print(i)

# And another function here for the user menu
selection = input(MENU_PROMPT)
while selection != 'q':
    if selection == "a":
        add()
    elif selection == "l":
        listMovies()
    elif selection == "f":
        x = input("Enter Movie Title :  ")
        findMovie(x)
    else:
        print('Unknown command. Please try again.')
    selection = input(MENU_PROMPT)
# Remember to run the user menu function at the end!